stages:

  data_load:
    cmd: python src/stages/data_load.py --config=params.yaml
    deps:
    - src/stages/data_load.py
    params:
    - base
    - data
    outs:
    - ${data.data_base_dir}/${data.dataset_name}/${data.tfrecords_dir}  # TODO: split train & test 
    - ${data.data_base_dir}/${data.dataset_name}/dataset_info.json

  build_embeddings:
    cmd: python src/stages/build_embeddings.py --config=params.yaml
    deps:
    - ${data.data_base_dir}/${data.dataset_name}/${data.tfrecords_dir} 
    params:
    - data
    outs:
    - ${data.data_base_dir}/${data.dataset_name}/${data.embeddings_dir} # TODO: add train/test folders

  build_index:
    cmd: python src/stages/build_index.py --config=params.yaml
    deps:
    - src/stages/build_index.py
    - ${data.data_base_dir}/${data.dataset_name}/${data.embeddings_dir} # TODO: change to train data
    params:
    - build_index
    outs:
    - ${base.models_dir}/${build_index.model_name}
    
  evaluate:
    cmd: python src/stages/evaluate.py --config=params.yaml
    deps:
    - ${base.models_dir}/${build_index.model_name}
    - ${data.data_base_dir}/${data.dataset_name}/${data.embeddings_dir}
    - src/stages/evaluate.py
    params:
    - evaluate
    metrics:
    - ${base.reports_dir}/${evaluate.metrics_map5}:
        cache: false
    plots:
    - ${base.reports_dir}/${evaluate.plots_metrics_all}:
        cache: false
    outs: 
    - ${base.reports_dir}/${evaluate.metrics_all}:
        cache: false
