stages:

  data_load:
    cmd: python src/stages/data_load.py --config=params.yaml
    deps:
    - src/stages/data_load.py
    params:
    - base
    - data_load
    outs:
    - ${base.dir_data_raw}/${data_load.dataset_csv}

  build_embeddings:
    cmd: python src/stages/featurize.py --config=params.yaml
    deps:
    - ...
    params:
    - base
    - featurize
    outs:
    - ${base.dir_data_processed}/${featurize.features_path}

  build_index:
    cmd: python src/stages/data_split.py --config=params.yaml
    deps:
    - ${base.dir_data_processed}/${featurize.features_path}
    - src/stages/data_split.py
    params:
    - base
    - data_split
    outs:
    - ${base.dir_data_processed}/${data_split.train_path}
    - ${base.dir_data_processed}/${data_split.test_path}
    
  evaluate:
    cmd: python src/stages/evaluate.py --config=params.yaml
    deps:
    - ${base.dir_models}/${train.model_name}
    - ${base.dir_data_processed}/${data_split.test_path}
    - src/stages/evaluate.py
    params:
    - base
    - data_split.test_path
    - evaluate
    - featurize.target_column
    outs:
    - ${base.dir_reports}/${evaluate.confusion_matrix_png}
    metrics:
    - ${base.dir_reports}/${evaluate.metrics_file}
    plots:
    - ${base.dir_reports}/${evaluate.plots_file}
